name: filers
description: Filers that handle file objects, Floaters which handle bytes data and similar objects
version: 0.0.1
publish_to: "none"
homepage: https://github.com/RagehAz/filers.git
# --------------------------------------------------------------------------------
environment:
  sdk: ">=2.10.5 <3.0.0"
  flutter: ">=1.17.0"
# --------------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter
 # ------------------------------------
  path: ^1.8.0
  path_provider: ^2.0.6
  image: ^3.0.8
  http: ^0.13.4
  flutter_svg: ^1.0.3
  # ------------------------------------
  mapper:
    git:
      url: https://github.com/RagehAz/mapper.git
  stringer:
    git:
      url: https://github.com/RagehAz/stringer.git
  numeric:
    git:
      url: https://github.com/RagehAz/numeric.git
  rest:
    git:
      url: https://github.com/RagehAz/rest.git
  space_time:
    git:
      url: https://github.com/RagehAz/space_time.git
# ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
# --------------------------------------------------------------------------------
flutter:
# --------------------------------------------------------------------------------
